POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RVc2VyIiwiaWQiOiI1ZjAyZTQyZDQ1MTJlODc2MDRiOTcxZWMiLCJpYXQiOjE1OTQxMTUxNDR9.G-4yIp5ZEfH9TlVOwlNNWsGoDukWBFH1T5h6ln1di84

{
    "title": "its fun!!!!!!",
    "author": "Mattias Petter Johansson",
    "url": "https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q",
    "likes": "5"
    

}